{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mdf.fullname" . }}-api
  labels:
    {{- include "mdf.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
  selector:
    {{- include "mdf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}

