apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mdf.fullname" . }}-config
  labels:
    {{- include "mdf.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.api.env.APP_ENV | quote }}
  API_PORT: {{ .Values.api.env.API_PORT | quote }}
  MODEL_ARTIFACT_PATH: {{ .Values.api.env.MODEL_ARTIFACT_PATH | quote }}
  MODEL_VERSION: {{ .Values.api.env.MODEL_VERSION | quote }}
  CORS_ORIGINS: {{ .Values.api.env.CORS_ORIGINS | quote }}

