{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mdf.fullname" . }}
  labels:
    {{- include "mdf.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- if $.Values.dashboard.enabled }}
          - path: {{ .paths.dashboard.path }}
            pathType: {{ .paths.dashboard.pathType }}
            backend:
              service:
                name: {{ include "mdf.fullname" $ }}-dashboard
                port:
                  name: http
          {{- end }}
          {{- if $.Values.api.enabled }}
          - path: {{ .paths.api.path }}
            pathType: {{ .paths.api.pathType }}
            backend:
              service:
                name: {{ include "mdf.fullname" $ }}-api
                port:
                  name: http
          {{- end }}
          {{- if $.Values.mlflow.enabled }}
          - path: {{ .paths.mlflow.path }}
            pathType: {{ .paths.mlflow.pathType }}
            backend:
              service:
                name: {{ include "mdf.fullname" $ }}-mlflow
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}

