{{- if not .Values.database.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mdf.fullname" . }}-database
  labels:
    {{- include "mdf.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "mdf.databaseUrl" . | quote }}
{{- end }}

